version: 1.1.{build}-{branch}

build: false

environment:
  matrix:
    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "32"
      platform: x86

    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "32"
      platform: x64

    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "64"
      platform: x64

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "32"
      platform: x86

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "32"
      platform: x64

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "64"
      platform: x64

init:
  - "ECHO %PYTHON_ARCH%"
  - "ECHO %PYTHON_VERSION%"
  - "ECHO %MINICONDA%"
  - "ECHO %APPVEYOR_BUILD_FOLDER%"
  - "ECHO %PYTHONPATH%"

install:
  - "%MINICONDA%\\Scripts\\conda install numpy -y -q"
  - "%MINICONDA%\\Scripts\\conda install pyqt -y -q"
  - "%MINICONDA%\\Scripts\\conda install pip -y -q"
  - "cd %APPVEYOR_BUILD_FOLDER%"
  - "%MINICONDA%\\Scripts\\pip.exe install -r dev-requirements.txt"
  - "SET PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%"
test_script:
  - "%MINICONDA%\\Scripts\\py.test -v --cov --timeout=100"
